"""
Direct gcode generator for Puffco Proxy V2 fit-test collar rings.
Ender-3 V3 Plus (Klipper), 0.4mm nozzle, PLA, 0.24mm layers.
Produces 3 gcode files for IDs: 21.5, 22.0, 22.5mm.
"""

import math
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

# --- Print config ---
LAYER_H       = 0.24       # mm
EXTRUSION_W   = 0.45       # mm (slightly wider than nozzle for good adhesion)
FILAMENT_D    = 1.75       # mm
PRINT_SPEED   = 40         # mm/s walls
TRAVEL_SPEED  = 150        # mm/s
HOTEND_TEMP   = 215        # °C PLA
BED_TEMP      = 60         # °C
SEGMENTS      = 72         # polygon approximation per circle

# Ender-3 V3 Plus bed center
BED_X, BED_Y  = 150.0, 150.0

# Extrusion per mm of travel (volumetric)
FILAMENT_AREA = math.pi * (FILAMENT_D / 2) ** 2
EXTRUDE_PER_MM = (LAYER_H * EXTRUSION_W) / FILAMENT_AREA  # mm filament per mm travel

OUTER_D = 30.0
HEIGHT  = 10.0
IDS     = [21.5, 22.0, 22.5]


def circle_path(cx, cy, radius, segments):
    pts = []
    for i in range(segments + 1):
        angle = 2 * math.pi * i / segments
        pts.append((cx + radius * math.cos(angle), cy + radius * math.sin(angle)))
    return pts


def start_gcode(hotend, bed, layer_count):
    return f"""; Puffco Proxy V2 fit-test collar — Ender-3 V3 Plus
; Generated by Djinn gen_collar_gcode.py
M82 ;absolute extrusion mode
M140 S0
M104 S0
START_PRINT EXTRUDER_TEMP={hotend} BED_TEMP={bed}
G92 E0
G92 E0
G1 F2400 E-0.8
;LAYER_COUNT:{layer_count}
"""


def end_gcode():
    return """M204 S20000
M106 S0
M106 P2 S0
END_PRINT
M82 ;absolute extrusion mode
M104 S0
;End of Gcode
"""


def gen_gcode(inner_d):
    ro = OUTER_D / 2.0
    ri = inner_d / 2.0
    layers = int(round(HEIGHT / LAYER_H))

    lines = [start_gcode(HOTEND_TEMP, BED_TEMP, layers)]
    e = 0.0

    for layer in range(layers):
        z = (layer + 1) * LAYER_H
        lines.append(f"\n; --- Layer {layer+1} z={z:.3f} ---")
        lines.append(f"G1 Z{z:.3f} F3000")

        speed_f = int(PRINT_SPEED * 60)

        # outer perimeter
        outer = circle_path(BED_X, BED_Y, ro, SEGMENTS)
        lines.append(f"G0 F{TRAVEL_SPEED*60} X{outer[0][0]:.3f} Y{outer[0][1]:.3f}")
        for i in range(1, len(outer)):
            x0, y0 = outer[i-1]
            x1, y1 = outer[i]
            dist = math.hypot(x1-x0, y1-y0)
            e += dist * EXTRUDE_PER_MM
            lines.append(f"G1 X{x1:.3f} Y{y1:.3f} E{e:.5f} F{speed_f}")

        # inner perimeter
        inner = circle_path(BED_X, BED_Y, ri, SEGMENTS)
        lines.append(f"G0 F{TRAVEL_SPEED*60} X{inner[0][0]:.3f} Y{inner[0][1]:.3f}")
        for i in range(1, len(inner)):
            x0, y0 = inner[i-1]
            x1, y1 = inner[i]
            dist = math.hypot(x1-x0, y1-y0)
            e += dist * EXTRUDE_PER_MM
            lines.append(f"G1 X{x1:.3f} Y{y1:.3f} E{e:.5f} F{speed_f}")

        # solid top/bottom layers (first 2 and last 2 — fill with concentric rings)
        if layer < 2 or layer >= layers - 2:
            r = ro - EXTRUSION_W
            while r > ri + EXTRUSION_W:
                ring = circle_path(BED_X, BED_Y, r, SEGMENTS)
                lines.append(f"G0 F{TRAVEL_SPEED*60} X{ring[0][0]:.3f} Y{ring[0][1]:.3f}")
                for i in range(1, len(ring)):
                    x0, y0 = ring[i-1]
                    x1, y1 = ring[i]
                    dist = math.hypot(x1-x0, y1-y0)
                    e += dist * EXTRUDE_PER_MM
                    lines.append(f"G1 X{x1:.3f} Y{y1:.3f} E{e:.5f} F{speed_f}")
                r -= EXTRUSION_W

    lines.append(end_gcode())
    return "\n".join(lines)


for id_mm in IDS:
    filename = os.path.join(OUTPUT_DIR, f"collar_ID{id_mm:.1f}mm.gcode")
    gcode = gen_gcode(id_mm)
    with open(filename, 'w') as f:
        f.write(gcode)
    lines = gcode.count('\n')
    print(f"Written: {filename}  ({lines} lines)")
